apiVersion: v1
kind: Pod
metadata:
  name: meupodazul
  labels:
    app: nginx
    version: blue
spec:
  containers:
  - name: meucontainer
    image: kubedevio/nginx-color:blue
    ports:
    - containerPort: 80