apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
  labels:
    app: nginx
    
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: meucontainer
        image: kubedevio/nginx-color:blue
        ports:
        - containerPort: 80